name: webserb-push-test
on: 
  push:
  pull_request:
jobs:
  build-and-test-webserver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: コンパイラと必要なツールのインストール
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make cmake g++ python3 python3-venv

      - name: webservをビルド
        run: |
          make
          ./webserv configrations/default.conf &
          sleep 1

      - name: google testをインストール
        run: |
          git clone https://github.com/google/googletest.git googletest/googletestcode

      - name: テストを実行
        run: |
          mkdir -p googletest/build
          cd googletest/build
          cmake ..
          cmake --build .
          ctest --verbose
